version: "3.8"
services:
  catalogdb:
    image: mongo
  basketdb:
    image: redis
  discount:
    image: postgres
  identitydb:
    image: mcr.microsoft.com/mssql/server
  orderdb:
    image: mcr.microsoft.com/mssql/server
  rabbitmq:
    image: rabbitmq:3.9.5-management
  catalog.api:
    image: catalog_api_image
    build: 
      context: .
      dockerfile: Catalog/Dockerfile
  identityserver.api:
    image: identityserver_api_image
    build: 
      context: .
      dockerfile: IdentityServer/AuthServerIds4/Dockerfile
  basket.api:
    image: basket_api_image
    build: 
      context: .
      dockerfile: Basket/Dockerfile
  discount.api:
    image: discount_api_image
    build: 
      context: .
      dockerfile: Discount/Dockerfile
  fakepayment.api:
    image: fakepayment_api_image
    build: 
      context: .
      dockerfile: FakePayment/Dockerfile
  order.api:
    image: order_api_image
    build: 
      context: .
      dockerfile: Order/Order.API/Dockerfile
volumes:
  catalogdb_volume:
  discount_volume:
  identitydb_volume:
  orderdb_volume: